sonar.projectKey=gym-web
sonar.projectName=Gym Web
sonar.projectVersion=1.1
sonar.host.url=http://localhost:9000
sonar.login=sqp_f1463d26cf34409f046510ddebb7683cae732552

# Backend source code only
sonar.sources=server/routes,server/models

# Test files
sonar.tests=server/tests

# Coverage report
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info

# Ignore folders
sonar.exclusions=**/node_modules/**,\
**/client/**,\
**/server/coverage/**,\
**/.scannerwork/**

# Ignore coverage generated files
sonar.coverage.exclusions=**/coverage/**,**/lcov-report/**

sonar.sourceEncoding=UTF-8