sonar.projectKey=gym-web
sonar.projectName=Gym Web
sonar.projectVersion=1.0

sonar.sources=client/src,server

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.login=sqp_16e5ff05a982f6c19624a6296e0823941f01fcab

sonar.exclusions=node_modules/**,build/**,dist/**sonar.projectKey=gym-web
sonar.projectName=Gym Web
sonar.projectVersion=1.0

sonar.sources=client/src,server

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.login=sqp_16e5ff05a982f6c19624a6296e0823941f01fcab

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/.scannerwork/**
